### ISSUE TITLE
permalink for the map mode

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#11]
Would be good if the map mode had a permalink, e.g freemeals.uk/map

would also be useful if this could tie into #12, e.g freemeals.uk/map/p/123 to show the provider with ID of 123, in map mode

**Comment by tomoakley** [comment]
would also be useful if this could tie into #12, e.g freemeals.uk/map/p/123 to show the provider with ID of 123, in map mode

**Comment by danvernon** [comment]
I will pick this up with #12
