### ISSUE TITLE
permalink for Selected provider

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#12]
Add permalink support for selected provider e.g freemeals.uk/p/123, so that if I load that url, it will automatically select the provider and show it in the right hand panel

**Comment by danvernon** [comment]
I will pick this up with #11

**Comment by tomoakley** [comment]
@danvernon how far did you get with this before switching over to implement the new design? Could someone else pick this up?

**Comment by danvernon** [comment]
@tomoakley its part of the design and structure im doing

**Comment by tomoakley** [comment]
Great, thanks

**Comment by tomoakley** [comment]
This is done
