### ISSUE TITLE
Add a loading state

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#18]
Currently when you select a filter or something the app doesn't do anything while the data loads. Would be nice if there could be a loading state for the data list with a spinner or something.

**Comment by adlradlr** [comment]
Hey, I can take a look into this issue.

**Comment by adlradlr** [comment]
Implemented in #28

**Comment by tomoakley** [comment]
Closed by #28, thanks @lmjcbs.
