### ISSUE TITLE
(Refactor) Container shared logic

### ISSUE THREAD

**Issue by kurt-culley** [tomoakley/freemeals.uk#26]
I think there's some opportunity to refactor some of the logic shared by the list and map containers, mainly around data fetching (perhaps could be moved out to a hook?)

**Comment by tomoakley** [comment]
I've added a data provider context component in #29, so that we're not duplicating the code for fetching the data. Let me know what you think.

**Comment by kurt-culley** [comment]
Hey I like what you've done so far, it's a nice improvement! I've left a couple comments on the pr for things to consider 🙂

**Comment by tomoakley** [comment]
Done (for now)
