### ISSUE TITLE
Fix mobile styling

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#3]
![IMG_05A6F17A8281-1](https://user-images.githubusercontent.com/782523/97051205-aa27ee80-1576-11eb-91e8-f463d186f2ac.jpeg)

App is completely broken on mobile

**Comment by jamiehowarth0** [comment]
Agreed. First move is implementing Bootstrap regardless of the JS platform.

**Comment by tomoakley** [comment]
Fixed / improved - for now.

I'll look at bootstrap but I'm focussed on getting the functionality in first (location search, data, etc). If another frontend dev could help with implementing bootstrap/another framework to improve the design that'd be great.
