### ISSUE TITLE
Geolocated results are slow to resolve, reload the page

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#31]
All of the results load, and then a few seconds later the geolocated results (if the user has permitted access to their location) will cause the page to reload. Would be great if it could be much smoother - i.e not showing/requesting all results and not reloading the page.

**Comment by elstob** [comment]
On it

**Comment by elstob** [comment]
The geolocation reload will be better implemented after the container refactor work in progress is done The only way I can see to block a refresh post geolocation is to set a flag when `react-geolocated` fires it's onSuccess/onError callbacks. If we have that flag we can block data loading until we know a user has been through the geolocation flow/doesn't have access to the geolocation API.

**Comment by tomoakley** [comment]
@elstob the refactoring is done and the new design is in. So a general improvement in the data fetching would be useful I think

**Comment by tomoakley** [comment]
I think for now this can be closed.
