### ISSUE TITLE
Use browser location API to get location and then use this as search params

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#4]
Currently the app returns all the data whenever anyone hits it. This isn't particuarly helpful if a user in Bournemouth is seeing results for Newcastle, Manchester and Cardiff. 

We can use the browser location APIs to grab the user location, and then use the lat/lng data to search the data and only return results near the user.

**Comment by kurt-culley** [comment]
Hey, I'm not sure if someone is already working on this, but it seemed like a fun problem so I've had a go at creating a solution anyway! If you're interested in seeing it, may I have permission to open a PR please?

**Comment by tomoakley** [comment]
Closed by #17
