### ISSUE TITLE
Mobile scrolling issues

### ISSUE THREAD

**Issue by domcoleman** [tomoakley/freemeals.uk#70]
1. The ProviderList component is still scrollable whilst viewing a Provider once the address bar is no longer visible.
2. The view on mobile is slightly too wide (on my Pixel 2), causing the page to need to be scrolled horizontally to press the close button.

![screen-20201026-143354](https://user-images.githubusercontent.com/46578754/97190424-96120600-179d-11eb-8e7d-0d161f59b4ae.gif)

**Comment by domcoleman** [comment]
Will make a PR with fixes later if there are no pending design changes?

**Comment by tomoakley** [comment]
no big design changes now. I think in #57 @danvernon is going to improve the Selected Pane, not sure if he's going to include this. tbh I'd just go for it if you have the time

**Comment by tomoakley** [comment]
I've fixed (some of) the responsive issues, but there's probably some cases I didn't spot.

**Comment by domcoleman** [comment]
I saw you'd made a commit yesterday with some of the changes so figured I'd leave it and test when you were done. All seems to be working fine now!
