### ISSUE TITLE
Disable scrolling of the main content when the Selected Pane is visible on mobile

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#8]
Currently the content behind the selected pane is scrollable on mobile. This makes scrolling the pane to see the details of the organisation difficult. We need to disable the scrolling here on this.

**Comment by tomoakley** [comment]
https://twitter.com/danvernon is working on this

**Comment by elstob** [comment]
Ah sorry @tomoakley started this before claiming it, you can ignore my PR if Dan has started. Will grab something else.

**Comment by tomoakley** [comment]
Thanks @elstob! 

Kind of related to this issue is https://github.com/tomoakley/freemeals.uk/issues/14 - I did mention to Daniel, not sure he's doing it already.

**Comment by tomoakley** [comment]
@elstob sent you a Twitter DM (I think it's you!) with a link to the Slack group I made

Edit: ah you've joined!
