### ISSUE TITLE
Add offline support and/or PWA integration

### ISSUE THREAD

**Issue by tomoakley** [tomoakley/freemeals.uk#9]
Would be really cool to have offline support for this. A lot of the people who are gonna be using it may not have a constant wifi/data connection so it would be good if they could use it even when offline. If it could be saved to a mobile homescreen and act like a Progressive Web App that'd be fantastic.

**Comment by marktdodds** [comment]
Looking into this

**Comment by tomoakley** [comment]
Draft PR up for this at #25

**Comment by marktdodds** [comment]
PR #25 ready to be reviewed and merged
